# Generated by Django 6.0.6 on 2026-07-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_contact', models.CharField(max_length=100)),
                ('preferred_location', models.CharField(blank=True, max_length=150)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'No Preference')], default='any', max_length=10)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text="A short bio/note about the student & what they're looking for")),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roommate_requests', to='properties.campus')),
                ('linked_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_requests', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
