# Generated by Django 6.0.7 on 2026-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
