# Generated by Django 6.0.6 on 2026-07-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-is_distress_sale', '-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='item',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional — e.g. 20.00 for 20% off, shown to buyers as a badge', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='distress_reason',
            field=models.CharField(blank=True, choices=[('relocating', 'Relocating'), ('graduating', 'Graduating Soon'), ('urgent_cash', 'Urgent Cash Need'), ('other', 'Other')], help_text='Optional — why the sale is urgent', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_distress_sale',
            field=models.BooleanField(default=False, help_text='Flag this if the seller needs to sell urgently'),
        ),
    ]
